FROM node:23-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

EXPOSE 3000

# NOTE: We intentionally start the app in development mode to allow for hot reloading!
CMD ["pnpm", "dev"]


